modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="christians_m_enchaments"
version="1.0.0"
displayName="Christian's Miscellaneous Enchaments"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="frank, MCreator"

[[dependencies.christians_m_enchaments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




